[0m00:10:43.451335 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105727380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107913890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079139d0>]}


============================== 00:10:43.454990 | db3c7824-60bb-4cb5-866d-946529057797 ==============================
[0m00:10:43.454990 [info ] [MainThread]: Running with dbt=1.10.4
[0m00:10:43.455402 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/ant/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt build', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:10:43.455737 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/ant/Documents/dk_data_ELT/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:10:43.457096 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.047301583, "process_in_blocks": "0", "process_kernel_time": 0.107464, "process_mem_max_rss": "104644608", "process_out_blocks": "0", "process_user_time": 0.622223}
[0m00:10:43.457365 [debug] [MainThread]: Command `dbt build` failed at 00:10:43.457315 after 0.05 seconds
[0m00:10:43.457577 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107902d70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107941eb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106fbd150>]}
[0m00:10:43.457753 [debug] [MainThread]: Flushing usage events
[0m00:10:43.856320 [debug] [MainThread]: An error was encountered while trying to flush usage events
